config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end
  root "homes#show"

  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do 
      post "follow" => "following_relationships#create"
      delete "unfollow" => "following_relationships#destroy"
    end
  end

end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"

  validates :follower_id, uniqueness: { scope: :followed_user_id }
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :content, polymorphic: true
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts
  has_many :followed_user_relationships,
            class_name: "FollowingRelationship",
            foreign_key: :follower_id

  has_many :followed_users, through: :followed_user_relationships

  has_many :follower_relationships,
            class_name: "FollowingRelationship",
            foreign_key: :followed_user_id

  has_many :followers, through: :follower_relationships

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def timeline
    Shout.where(user_id: [id] + followed_user_ids).order(created_at: :desc)
  end

  def following?(user)
    followed_users.include?(user)
  end

  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.delete(user)
  end

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  before_action :require_login
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @text_shout = TextShout.new
    @photo_shout = PhotoShout.new
    @shouts = current_user.shouts
    @followers = current_user.followers
    @followed_users = current_user.followed_users
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController

  def create
    user = User.find_by(username: params[:id])
    current_user.follow(user)

    redirect_to user
  end

  def destroy
    user = User.find_by(username: params[:id])
    current_user.unfollow(user)

    redirect_to current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :require_login

  def show
    @user = User.new
  end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username,:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def create
    current_user.shouts.create(shouts_params)
    redirect_to dashboard_path
  end
  private

  def shouts_params
    params.require(:shout).permit(:content).merge(user: current_user)
  end
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
 def create
   text_shout = TextShout.new(text_shout_params)
  current_user.shouts.create(content: text_shout)

  redirect_to dashboard_path
 
 end

 private

 def text_shouts_params
  params. require(:shout).permit(:body).merge(user: current_user)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(username: params[:id])
    @shouts = @user.shouts
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_sign_in_form.html.erb
<h2>Sign In</h2>

<%= form_for :session, url: session_path do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>

app/views/application/_sign_up_form.html.erb
<h2>Sign Up</h2>
<%= form_for @user do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email%>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>

<%= form_for @photo_shout  do |form| %>
  <%= form.file_field :body %>
  <%= form.submit "Shout" %>
<% end %>

<%= form_for @text_shout  do |form| %>
  <%= form.text_field :body %>
  <%= form.submit "Shout" %>
<% end %>

<%= render current_user.timeline %>
<%= render @shouts %>

app/views/homes/show.html.erb
<%= render "sign_in_form" %>
<%= render "sign_up_form", user: @user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if signed_in? %>
    <%= link_to "Sign out", session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_session_path %>
    <%= link_to "Sign up", new_user_path %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/shouts/_shout.html.erb
<%= div_for(shout) do %>
  <%= shout.content.body %> by <%= link_to shout.user.username, shout.user %>
<% end %>

app/views/users/_follow_button.html.erb
<% if @user != current_user %>
<div>
  <% if current_user.following?(@user) %>
    <%= button_to "Unfollow", follow_user_path(@user), method: :delete %>
  <% else %>
<%= button_to "Follow", follow_user_path(@user) %>
  <% end %>
</div>
<% end %>

app/views/users/_user.html.erb
<%= link_to user.username, user %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.email_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :username %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Shouts</h1>

<%= render "follow_button", user: @user %>

Following: <%= render  @user.followed_users %>

<%= render @shouts %>